let counter = 0; // sayacı tanımla

function changeText() {
    const buttonTexts = [
        "Artificial Intelligence (AI) is a rapidly advancing field of technology that has the potential to revolutionize many aspects of our lives. AI involves the development of intelligent machines that can perform tasks that typically require human intelligence, such as recognizing speech, interpreting images, and making decisions. The future of AI looks promising, with the potential to transform many industries, from healthcare to finance to transportation. In healthcare, for example, AI can assist doctors in diagnosing diseases, predicting patient outcomes, and developing personalized treatment plans. In finance, AI can help detect fraud, analyze market trends, and make investment decisions. In transportation, AI can enable self-driving cars that reduce accidents and traffic congestion. However, there are also concerns about the potential negative effects of AI, such as job displacement and privacy violations. To address these challenges, it is essential to invest in education and training programs that prepare people for the jobs of the future and develop regulations that ensure AI is developed and used responsibly. Despite these challenges, the future of AI looks promising, and it has the potential to transform many aspects of our lives for the better.",
        "The future of medicine holds immense promise as technology continues to advance and research expands. Emerging treatments such as gene editing, nanotechnology, and stem cell therapies are changing the landscape of healthcare. These cutting-edge technologies have the potential to revolutionize how we treat diseases and improve overall health outcomes. Additionally, the development of artificial intelligence (AI) and machine learning has the potential to transform the way medical diagnoses are made, and how healthcare is delivered. AI can help healthcare professionals to diagnose diseases more accurately and quickly, predict the likelihood of certain diseases, and create personalized treatment plans for individual patients. Advancements in medical technology will also continue to improve patient outcomes and reduce healthcare costs. Telemedicine and remote patient monitoring are becoming increasingly popular, which means that patients can receive medical care from the comfort of their own homes. In conclusion, the future of medicine is bright, with a focus on personalized treatments, precision medicine, and the integration of technology to improve healthcare outcomes. As medical research and technology continue to advance, we can expect to see even more groundbreaking treatments and cures for diseases.",
        "Draco Malfoy is one of the most prominent characters in the Harry Potter series. He is a complex character, whose personality is shaped by his upbringing, values, and social status. Malfoy is portrayed as arrogant, cunning, and prejudiced against Muggle-borns and those who are not purebloods. Malfoy's personality is largely shaped by his family's beliefs and values. He is taught from a young age that being a pureblood is superior, and he adopts this belief as his own. His arrogance and entitlement are a result of his privileged upbringing, which leads him to look down on those who are not of his social status. However, as the series progresses, Malfoy's character becomes more nuanced. He is forced to confront the reality of the world he lives in and the actions of those around him. Malfoy's internal struggle is exemplified in his decision to not identify Harry Potter during the Battle of Hogwarts, despite being given the opportunity to do so. This act suggests that Malfoy is not entirely committed to his family's beliefs and may have a conscience that is at odds with his upbringing. In conclusion, Malfoy is a character that embodies the complexities of human nature. He is a product of his upbringing, but his character is not entirely defined by his family's beliefs. Malfoy's journey throughout the series illustrates how individuals can struggle with their identity and beliefs, and how they can ultimately choose their own path."
    ];

    const button = document.getElementById("metin-main");

    button.innerHTML = buttonTexts[counter % buttonTexts.length];
    counter++;

}